-- Phase 1: Schema design
-- Sketch the ER diagram first, then fill this in table by table.
--
-- Planned tables:
--   users            (mirrors auth.users, adds plan_tier cache column)
--   plans             (free / basic / premium definitions)
--   subscriptions     (user_id, plan_id, status, razorpay_subscription_id)
--   courses           (title, tier_required)
--   lessons           (course_id, tier_required, content_url)
--   progress          (user_id, lesson_id, completed_at)
--   usage_events      (telemetry: user_id, event_type, device, page, created_at)
--   ad_impressions    (user_id, shown_at) -- for ad frequency capping
--   admin_logs        (actor_id, action, target, created_at)
--
-- Add RLS policies in a separate migration file once tables are in place:
--   e.g. 00000000000001_rls_policies.sql
